"""Add writing performance levels table

Revision ID: 60750a0defae
Revises: bd391563fda2
Create Date: 2025-04-25 12:42:54.338062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60750a0defae'
down_revision = 'bd391563fda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writing_performance_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criteria_id'], ['writing_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writing_performance_levels')
    # ### end Alembic commands ###
