"""Add subscription_date to users table

Revision ID: 697fd5dc6f6f
Revises: dddc169f2830
Create Date: 2025-04-25 17:24:26.230602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697fd5dc6f6f'
down_revision = 'dddc169f2830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_date')

    # ### end Alembic commands ###
