"""add writing fields

Revision ID: add_writing_fields
Revises: update_contact_requests_table
Create Date: 2024-03-08 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'add_writing_fields'
down_revision = 'update_contact_requests_table'
branch_labels = None
depends_on = None


def upgrade():
    # Get the bind connection
    connection = op.get_bind()
    inspector = Inspector.from_engine(connection)
    
    # Get existing columns in user_answers table
    columns = [column['name'] for column in inspector.get_columns('user_answers')]
    
    # Add writing_score column if it doesn't exist
    if 'writing_score' not in columns:
        op.add_column('user_answers', sa.Column('writing_score', sa.Float(), nullable=True))
    
    # Add is_evaluated column if it doesn't exist
    if 'is_evaluated' not in columns:
        op.add_column('user_answers', sa.Column('is_evaluated', sa.Boolean(), nullable=True, server_default='false'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('user_answers', 'is_evaluated')
    except Exception:
        pass
        
    try:
        op.drop_column('user_answers', 'writing_score')
    except Exception:
        pass
    # ### end Alembic commands ### 