"""add phone and city to users

Revision ID: add_phone_and_city_to_users
Revises: update_contact_requests_table
Create Date: 2024-03-08 19:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'add_phone_and_city_to_users'
down_revision = 'update_contact_requests_table'
branch_labels = None
depends_on = None


def upgrade():
    # Get the bind connection
    connection = op.get_bind()
    inspector = Inspector.from_engine(connection)
    
    # Get existing columns in users table
    columns = [column['name'] for column in inspector.get_columns('users')]
    
    # Add phone column if it doesn't exist
    if 'phone' not in columns:
        op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    
    # Add city column if it doesn't exist
    if 'city' not in columns:
        op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('users', 'city')
    except Exception:
        pass
        
    try:
        op.drop_column('users', 'phone')
    except Exception:
        pass
    # ### end Alembic commands ### 