"""Ajout de l'attribut user_role au modèle Test

Revision ID: d162e215b2c7
Revises: 44b9e38ed4e8
Create Date: 2024-12-20 15:54:10.545624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd162e215b2c7'
down_revision = '44b9e38ed4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###
