"""Make test_id nullable in questions table and update relationships

Revision ID: dddc169f2830
Revises: 60750a0defae
Create Date: 2025-04-25 17:07:49.541351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = 'dddc169f2830'
down_revision = '60750a0defae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Mettre à jour les valeurs NULL dans test_sections.content
    op.execute(text("UPDATE test_sections SET content = 'Contenu par défaut' WHERE content IS NULL"))
    
    # Mettre à jour les valeurs NULL dans writing_criteria.description
    op.execute(text("UPDATE writing_criteria SET description = 'Description par défaut' WHERE description IS NULL"))
    
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('test_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('test_sections', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('writing_criteria', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writing_criteria', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('test_sections', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('test_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
